# Github Actions configuration
name: CI

permissions: {}

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master and ci branches
  push:
    branches:
      - master
      - "*/ci"
  pull_request:
    branches:
      - master

env:
  MAKEFLAGS: -j 2

jobs:
  build-22_04:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        build:
        - cc: gcc
          configure:
          install: libtool autoconf automake autopoint pkg-config gettext libgtk2.0-dev libexif-dev
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3
        - cc: clang
          configure:
          install: clang libtool autoconf automake autopoint pkg-config gettext libgtk2.0-dev libexif-dev
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3
        - cc: gcc
          configure: --with-gtk3
          install: libtool autoconf automake autopoint pkg-config gettext libgtk-3-dev libexif-dev
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3
        - cc: clang
          configure: --with-gtk3
          install: clang libtool autoconf automake autopoint pkg-config gettext libgtk-3-dev libexif-dev
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3

    steps:
    - uses: actions/checkout@v3
    - name: 'install deps'
      run: sudo apt-get update -y; sudo apt-get install -y --no-install-suggests --no-install-recommends ${{ matrix.build.install }}
    - name: 'configure'
      run: autoreconf -sif && ./configure --prefix="$PWD"/install --disable-dependency-tracking CFLAGS="${{ matrix.build.cflags }}" CC="${{ matrix.build.cc }}" ${{ matrix.build.configure }}
    - name: 'build'
      run: make
    - name: 'test'
      run: make check
    - name: 'install'
      run: make install

  build-20_04:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        build:
        - cc: gcc
          configure:
          install: libtool autoconf automake autopoint pkg-config gettext libgtk2.0-dev libexif-dev
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3
        - cc: clang
          configure:
          install: clang libtool autoconf automake autopoint pkg-config gettext libgtk2.0-dev libexif-dev
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3
        - cc: gcc
          configure: --with-gtk3
          install: libtool autoconf automake autopoint pkg-config gettext libgtk-3-dev libexif-dev
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3
        - cc: clang
          configure: --with-gtk3
          install: clang libtool autoconf automake autopoint pkg-config gettext libgtk-3-dev libexif-dev
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3

    steps:
    - uses: actions/checkout@v3
    - name: 'install deps'
      run: sudo apt-get update -y; sudo apt-get install -y --no-install-suggests --no-install-recommends ${{ matrix.build.install }}
    - name: 'configure'
      run: autoreconf -sif && ./configure --prefix="$PWD"/install --disable-dependency-tracking CFLAGS="${{ matrix.build.cflags }}" CC="${{ matrix.build.cc }}" ${{ matrix.build.configure }}
    - name: 'build'
      run: make
    - name: 'test'
      run: make check
    - name: 'install'
      run: make install

  build-macosx:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        build:
        - cc: gcc
          configure:
          install: automake gtk+ libexif
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3
        - cc: clang
          configure:
          install: automake gtk+ libexif
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3
        - cc: gcc
          configure: --with-gtk3
          install: automake gtk+3 libexif
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3
        - cc: clang
          configure: --with-gtk3
          install: automake gtk+3 libexif
          cflags: -Wall -Wextra -Werror -Wno-error=deprecated-declarations -O3

    steps:
    - uses: actions/checkout@v3
    - name: 'install deps'
      run: brew update && brew install ${{ matrix.build.install }}
    - name: 'configure'
      run: autoreconf -sif && ./configure --prefix="$PWD"/install-root --disable-dependency-tracking CFLAGS="${{ matrix.build.cflags }}" CC="${{ matrix.build.cc }}" ${{ matrix.build.configure }}
    - name: 'build'
      run: make
    - name: 'test'
      run: make check
    - name: 'install'
      run: make install
